### ISSUE TITLE
AttributeError: `SyncMainDataDictionary` instance has no attribute `free_space_on_disk'Issue Title`

### ISSUE THREAD

**Issue by LimeDrive** [LimeDrive/qb-auto-delt#6]
```log
INFO  ::  2021-04-23 03:14:03,221 - __main__ - Conection with qBittorrent tested OK : v4.1.7
INFO  ::  2021-04-23 03:14:03,325 - __main__ - Conection with qBt Web Api tested OK : 2.2
INFO  ::  2021-04-23 03:15:03,594 - __main__ - Disk Space at 27.9 GiB - Your allow to fill up 18 GiB before deleting script process
INFO  ::  2021-04-23 03:15:03,595 - __main__ - Script will recheck your disk space in - 300 - seconds
````
Error :
```py
Traceback (most recent call last):
  File "/Users/**********/GitProject/qb-auto-delt/main.py", line 177, in <module>
    if diskUsageControl():
  File "/Users/**********/GitProject/qb-auto-delt/main.py", line 51, in diskUsageControl
    free = round(i.server_state.free_space_on_disk / 2 ** 30)
  File "/usr/local/lib/python3.9/site-packages/qbittorrentapi/_attrdict.py", line 153, in __getattr__
    raise AttributeError(
AttributeError: 'SyncMainDataDictionary' instance has no attribute 'free_space_on_disk'
````
```log
(work_env) ➜  qb-auto-delt git:(Lime02) ✗ /Users/**********/GitProject/qb-auto-delt/work_env/bin/python /Users/**********/GitProject/qb-auto-delt/main.py
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '.ovh'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
INFO  ::  2021-04-23 03:25:16,117 - __main__ - Conection with qBittorrent tested OK : v4.1.7
INFO  ::  2021-04-23 03:25:16,224 - __main__ - Conection with qBt Web Api tested OK : 2.2
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ovh'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
INFO  ::  2021-04-23 03:26:16,717 - __main__ - Conection with qBittorrent tested OK : v4.1.7
INFO  ::  2021-04-23 03:26:16,802 - __main__ - Conection with qBt Web Api tested OK : 2.2
INFO  ::  2021-04-23 03:26:17,051 - __main__ - Disk Space at 27.9 GiB - Your allow to fill up 18 GiB before deleting script process
INFO  ::  2021-04-23 03:26:17,052 - __main__ - Script will recheck your disk space in - 60 - seconds
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '.ovh'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
INFO  ::  2021-04-23 03:28:17,530 - __main__ - Conection with qBittorrent tested OK : v4.1.7
INFO  ::  2021-04-23 03:28:17,580 - __main__ - Conection with qBt Web Api tested OK : 2.2
````
Prob with the disk usage api, test on remote instance...
I try to fix it with timeout, but not sure thats gone work. Up to 10 min, i still get the same error.

**Comment by LimeDrive** [comment]
#7  Test a faire sur un remote mais devrait fix le problème
